# Generated by Django 5.0.7 on 2025-01-23 18:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
